-- 코드를 입력하세요
SELECT HISTORY_ID,
ROUND(CASE
    WHEN DURATION_TYPE LIKE '7%' THEN CAR.DAILY_FEE*(DATEDIFF(HIS.END_DATE,HIS.START_DATE)+1)*(1-PLAN.DISCOUNT_RATE/100)
    WHEN DURATION_TYPE LIKE '30%' THEN CAR.DAILY_FEE*(DATEDIFF(HIS.END_DATE,HIS.START_DATE)+1)*(1-PLAN.DISCOUNT_RATE/100)
    WHEN DURATION_TYPE LIKE '90%' THEN CAR.DAILY_FEE*(DATEDIFF(HIS.END_DATE,HIS.START_DATE)+1)*(1-PLAN.DISCOUNT_RATE/100)
    ELSE CAR.DAILY_FEE*(DATEDIFF(HIS.END_DATE,HIS.START_DATE)+1)
END,0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
JOIN CAR_RENTAL_COMPANY_CAR CAR
ON HIS.CAR_ID = CAR.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON PLAN.CAR_TYPE = CAR.CAR_TYPE 
AND PLAN.DURATION_TYPE =
CASE
    WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE)+1 >=90 THEN '90일 이상'
    WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE)+1 >=30 THEN '30일 이상'
    WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE)+1 >=7 THEN '7일 이상'
END
WHERE CAR.CAR_TYPE='트럭'
ORDER BY FEE DESC, HIS.HISTORY_ID DESC