-- 코드를 입력하세요
SELECT APNT_NO,PT_NAME,PT.PT_NO,APT.MCDP_CD,DR_NAME,APNT_YMD
FROM APPOINTMENT AS APT
JOIN DOCTOR AS DR
ON APT.MDDR_ID=DR.DR_ID
JOIN PATIENT AS PT
ON APT.PT_NO = PT.PT_NO
WHERE APNT_CNCL_YN ='N'
    AND APNT_YMD LIKE '2022-04-13%' 
    AND DR.MCDP_CD = 'CS'
ORDER BY APNT_YMD